version: "2.2"
services:
    proxy:
      image: 'nginx'
      container_name: reverse_proxy
      restart: always
      network_mode: "host"
      volumes:
        - /app/nginx/config/nginx.conf:/etc/nginx/nginx.conf
        - /app/nginx/config/ssl:/etc/nginx/ssl
