version "2.2"
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: always
    hostname: 'jenkins.gbc.ca'
    ports:
      - "8443:8443"
      - "8000:8000"
      - "50001:50001"
    environment:
      JAVA_OPTS: '-Duser.timezone=America/Toronto'
    volumes:
       - '/var/jenkins/home:/var/jenkins_home'
       - '/var/run/docker.sock:/var/run/docker.sock'
       - '/app/jenkins/config/ssh:/root/.ssh'
       - '/app/jenkins/config/docker:/root/.docker'
       - '/app/jenkins/config/jfrog:/root/.jfrog'
       - '/etc/localtime:/etc/localtime'
