version: "2.2"
services:
    artifactory:
      image: 'docker.bintray.io/jfrog/artifactory-oss'
      container_name: artifactory
      restart: always
      environment:
        - DB_TYPE=postgresql
        - DB_HOST=db
        - DB_USER=gbc
        - DB_PASSWORD=gbcpassword
        - EXTRA_JAVA_OPTIONS=-Duser.timezone=America/Toronto
      ports:
        - '8081:8081'
      volumes:
        - '/app/artifactory/data:/var/opt/jfrog/artifactory'
    db:
      image: 'postgres'
      container_name: artifactory_db
      restart: always
      environment:
        - POSTGRES_USER=gbc
        - POSTGRES_PASSWORD=gbcpassword
        - POSTGRES_DB=artifactory
      volumes:
        - '/app/artifactory/postgresql:/var/lib/postgresql/data'
